networks:
  zenoh-net:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    networks:
      - zenoh-net

  emqx:
    image: emqx:5.8
    container_name: emqx
    ports:
      - "1884:1883"   # MQTT TCP
      - "18084:18083" # Dashboard (optional)
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
      - EMQX_AUTHORIZATION__NO_MATCH=allow
      - EMQX_LOG__LEVEL=info
    networks:
      - zenoh-net

  hivemq:
    image: hivemq/hivemq-ce:latest
    container_name: hivemq
    ports:
      - "1885:1883"   # MQTT TCP
      - "8081:8080"   # Dashboard (optional)
    networks:
      - zenoh-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - zenoh-net

  router1:
    image: eclipse/zenoh:1.5.1
    container_name: router1
    command: ["-c", "/etc/zenoh/router1.json5"]
    ports:
      - "7447:7447" # TCP listener exposed to host
    volumes:
      - ./config/router1.json5:/etc/zenoh/router1.json5:ro
    environment:
      RUST_LOG: info
    networks:
      - zenoh-net

  router2:
    image: eclipse/zenoh:1.5.1
    container_name: router2
    command: ["-c", "/etc/zenoh/router2.json5"]
    ports:
      - "7448:7447" # expose TCP listener to host for router2
    volumes:
      - ./config/router2.json5:/etc/zenoh/router2.json5:ro
    environment:
      RUST_LOG: info
    networks:
      - zenoh-net
    depends_on:
      - router1

  router3:
    image: eclipse/zenoh:1.5.1
    container_name: router3
    command: ["-c", "/etc/zenoh/router3.json5"]
    ports:
      - "7449:7447" # expose TCP listener to host for router3
    volumes:
      - ./config/router3.json5:/etc/zenoh/router3.json5:ro
    environment:
      RUST_LOG: info
    networks:
      - zenoh-net
    depends_on:
      - router1
